name: Test and Deploy
on:
    push:
        branches:
            - main

jobs:
    test-html:
        runs-on: ubuntu-latest
        steps:
            - name: Check code
              uses: actions/checkout@v3

            - name: Installer HTML-validator
              run: npm install -g html-validator-cli

            - name: Test HTML
              run: html-validator --file=index.html --verbose

    deploy-to-vercel:
        needs: test-html
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Vercel
              run: echo "Vercel is no deploying, magic is happening here"
